#!/usr/bin/python3
""" Script that lists most recent 10 commits on
Github repo"""


import requests
from sys import argv
if __name__ == '__main__':
    url = "https://api.github.com/repos/{}/{}/commits"\
            .format(argv[1], argv[2])

    req = requests.get(url).json()
    lim = 10 if len(req) > 10 else len(req)
    for x in req[0:lim]:
        print("{}: {}".format(x['sha'], x['commit']['author']['name']))
